# Generated by Django 3.0.7 on 2024-09-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
